In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('D:\FLIGHT PRICE PREDICTOR\BASE\clean_flight_dataset1.csv')

In [3]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [4]:
df["DISTANCE_BIN"] = pd.qcut(df["DISTANCE"], q=5)

In [5]:
df["DISTANCE_BIN"].value_counts()

DISTANCE_BIN
(316.0, 516.0]      990129
(30.999, 316.0]     984416
(757.0, 1068.0]     982803
(1068.0, 2130.0]    982009
(516.0, 757.0]      976996
Name: count, dtype: int64

In [6]:
df.to_csv('D:\FLIGHT PRICE PREDICTOR\BASE\clean_flight_dataset1.csv', index=False)

In [7]:
df.shape

(4916353, 19)

In [8]:
df.head(10)

,MONTH,DAY,DAY_OF_WEEK,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_TIME,DISTANCE,FARE,AIRLINE,DEP_HOUR,ARR_HOUR,DEP_MIN,ARR_MIN,IS_WEEKEND,ROUTE,DEP_TIME_BIN,IS_HOLIDAY_SEASON,FARE_PER_MILE,DISTANCE_BIN
0,1,1,4,ANC,SEA,205.0,1448,266.42,Alaska Airlines Inc.,0,4,5,30,0,ANC_SEA,Early_Morning,0,0.183992,"(1068.0, 2130.0]"
1,1,1,4,SEA,ANC,235.0,1448,267.21,Alaska Airlines Inc.,0,3,25,20,0,SEA_ANC,Early_Morning,0,0.184537,"(1068.0, 2130.0]"
2,1,1,4,SFO,MSP,217.0,1589,288.16,Delta Air Lines Inc.,0,6,25,2,0,SFO_MSP,Early_Morning,0,0.181347,"(1068.0, 2130.0]"
3,1,1,4,LAS,MSP,181.0,1299,247.22,Spirit Air Lines,0,5,25,26,0,LAS_MSP,Early_Morning,0,0.190316,"(1068.0, 2130.0]"
4,1,1,4,SFO,DFW,195.0,1464,269.36,American Airlines Inc.,0,5,30,45,0,SFO_DFW,Early_Morning,0,0.183989,"(1068.0, 2130.0]"
5,1,1,4,LAS,ATL,221.0,1747,312.09,Delta Air Lines Inc.,0,7,30,11,0,LAS_ATL,Early_Morning,0,0.178643,"(1068.0, 2130.0]"
6,1,1,4,DEN,ATL,173.0,1199,229.87,Delta Air Lines Inc.,0,5,30,23,0,DEN_ATL,Early_Morning,0,0.191718,"(1068.0, 2130.0]"
7,1,1,4,LAX,MSP,214.0,1535,280.16,Delta Air Lines Inc.,0,6,35,9,0,LAX_MSP,Early_Morning,0,0.182515,"(1068.0, 2130.0]"
8,1,1,4,SLC,ATL,215.0,1590,287.96,Delta Air Lines Inc.,0,6,40,15,0,SLC_ATL,Early_Morning,0,0.181107,"(1068.0, 2130.0]"
9,1,1,4,SEA,MSP,189.0,1399,259.75,Delta Air Lines Inc.,0,5,40,49,0,SEA_MSP,Early_Morning,0,0.185668,"(1068.0, 2130.0]"

In [9]:
df.drop('FARE_PER_MILE', axis=1, inplace=True)

In [10]:
df.to_csv('D:\FLIGHT PRICE PREDICTOR\BASE\clean_flight_dataset1.csv', index=False)

In [11]:
df.head(10)

,MONTH,DAY,DAY_OF_WEEK,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_TIME,DISTANCE,FARE,AIRLINE,DEP_HOUR,ARR_HOUR,DEP_MIN,ARR_MIN,IS_WEEKEND,ROUTE,DEP_TIME_BIN,IS_HOLIDAY_SEASON,DISTANCE_BIN
0,1,1,4,ANC,SEA,205.0,1448,266.42,Alaska Airlines Inc.,0,4,5,30,0,ANC_SEA,Early_Morning,0,"(1068.0, 2130.0]"
1,1,1,4,SEA,ANC,235.0,1448,267.21,Alaska Airlines Inc.,0,3,25,20,0,SEA_ANC,Early_Morning,0,"(1068.0, 2130.0]"
2,1,1,4,SFO,MSP,217.0,1589,288.16,Delta Air Lines Inc.,0,6,25,2,0,SFO_MSP,Early_Morning,0,"(1068.0, 2130.0]"
3,1,1,4,LAS,MSP,181.0,1299,247.22,Spirit Air Lines,0,5,25,26,0,LAS_MSP,Early_Morning,0,"(1068.0, 2130.0]"
4,1,1,4,SFO,DFW,195.0,1464,269.36,American Airlines Inc.,0,5,30,45,0,SFO_DFW,Early_Morning,0,"(1068.0, 2130.0]"
5,1,1,4,LAS,ATL,221.0,1747,312.09,Delta Air Lines Inc.,0,7,30,11,0,LAS_ATL,Early_Morning,0,"(1068.0, 2130.0]"
6,1,1,4,DEN,ATL,173.0,1199,229.87,Delta Air Lines Inc.,0,5,30,23,0,DEN_ATL,Early_Morning,0,"(1068.0, 2130.0]"
7,1,1,4,LAX,MSP,214.0,1535,280.16,Delta Air Lines Inc.,0,6,35,9,0,LAX_MSP,Early_Morning,0,"(1068.0, 2130.0]"
8,1,1,4,SLC,ATL,215.0,1590,287.96,Delta Air Lines Inc.,0,6,40,15,0,SLC_ATL,Early_Morning,0,"(1068.0, 2130.0]"
9,1,1,4,SEA,MSP,189.0,1399,259.75,Delta Air Lines Inc.,0,5,40,49,0,SEA_MSP,Early_Morning,0,"(1068.0, 2130.0]"

In [12]:
df.shape

(4916353, 18)